# HOST_SSH_KEY="$(cat ~/.ssh/id_rsa)" docker-compose up

version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - HOST_SSH_KEY=${HOST_SSH_KEY}
    ports:
      - "80:3000"
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://perdiem:123456@mongo:27017/perdiem?authSource=admin
      PORT: 3000

  #docker sets the hostname automatically from the service name
  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    environment:
      - MONGO_INITDB_ROOT_USERNAME=perdiem
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=perdiem
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"


secrets:
  host_ssh_key:
    file: ~/.ssh/id_rsa

volumes:
  data:
