- hosts: "{{ DEPLOY_ENV }}"
  remote_user: root
  become: yes

  tasks:
    - name: Ensure Docker Network is present
      docker_network:
        name: perdiem_network
        state: present

    - name: Start the Mongo Container
      docker_container:
        name: perdiem-mongo
        restart_policy: always
        image: mongo:latest
        state: started
        networks:
          - name: perdiem_network
        env:
          MONGO_INITDB_ROOT_USERNAME: "perdiem"
          MONGO_INITDB_ROOT_PASSWORD: "123456"
          MONGO_INITDB_DATABASE: "perdiem"
        volumes:
          - data:/data/db
        ports:
          - "27017:27017"

    - name: Start the App Container
      docker_container:
        name: perdiem-${{ DEPLOY_ENV }}
        restart_policy: always
        image: "bigbelmar/perdiem-${{ DEPLOY_ENV }}"
        state: started
        pull: true
        networks:
          - name: perdiem_network
        env:
          ROOT_URL: http://0.0.0.0/
          MONGO_URL: mongodb://perdiem:123456@perdiem-mongo/perdiem?authSource=admin
          PORT: "3000"
        ports:
          - "3000:3000"
        volumes:
          - ./config:/app/bundle/config