- hosts: all
  remote_user: root
  become: yes

  tasks:
  - name: Create Nginx data volume
    docker_volume:
      name: nginx-data
      driver: local

  - name: Start the Nginx Container
    docker_container:
      name: nginx
      restart_policy: always
      image: nginx:latest
      state: started
      ports:
        - "80:80"
      volumes:
        - "nginx-data:/usr/share/nginx/html:ro"